[tool.poetry]
name = "pylette"
version = "0.4.0"
description = "A Python library for extracting color palettes from images."
authors = ["Ivar Stangeby"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
